// <auto-generated/>
using Microsoft.AspNetCore.Components;

namespace RazorApp.Shared
{
    public partial class LifeCycle
    {
        private List<string> _steps = new List<string>();
        private string _apiResponse;
        private string? _var = "valeur Initial";
        protected override void OnInitialized()
        {
            _steps.Add(nameof(OnInitialized));
            Console.WriteLine("OnInitialized - DEBUT");
            base.OnInitialized();
            Console.WriteLine("OnInitialized - FIN");

        }

        protected override async Task OnInitializedAsync()
        {
            _steps.Add(nameof(OnInitializedAsync));

            Console.WriteLine("OnInitializedAsync - DEBUT");
            await base.OnInitializedAsync();

            Console.WriteLine("OnInitializedAsync - FIN");

        }

        protected override void OnParametersSet()
        {
            _steps.Add(nameof(OnParametersSet));
            Console.WriteLine("OnParametersSet - DEBUT");
            base.OnParametersSet();
            Console.WriteLine("OnParametersSet - FIN");
        }

        protected override async Task OnParametersSetAsync()
        {
            _steps.Add(nameof(OnParametersSetAsync));
            Console.WriteLine("OnParametersSetAsync - DEBUT ");
            await base.OnParametersSetAsync();
            Console.WriteLine("OnParametersSetAsync - DEBUT ");

        }

        protected override void OnAfterRender(bool firstRender)
        {
            _steps.Add(nameof(OnAfterRender));
            Console.WriteLine("OnAfterRender - DEBUT");
            base.OnAfterRender(firstRender);
            Console.WriteLine("OnAfterRender - FIN");

        }

        protected override async Task OnAfterRenderAsync(bool firstRender)
        {
            Console.WriteLine($"OnAfterRenderAsync - DEBUT (First? {firstRender})");
            if (firstRender)
            {
                await Task.Delay(5000);
                _apiResponse = "Réponse de l'Api";
                StateHasChanged(); // l'etat de mon composant a change  tu peux faire le reflesh

            }
            await base.OnAfterRenderAsync(firstRender);
            Console.WriteLine($"OnAfterRenderAsync - FIN (First {firstRender})");

        }

        public override async Task SetParametersAsync(ParameterView parameters)
        {
            _steps.Add(nameof(SetParametersAsync));
            Console.WriteLine("SetParametersAsync - DEBUT");
            await base.SetParametersAsync(parameters);
            Console.WriteLine("SetParametersAsync - FIN");

        }

        protected override bool ShouldRender()
        {
            _steps.Add(nameof(ShouldRender));

            Console.WriteLine("ShouldRender - DEBUT");
            var _result = false; //base.ShouldRender();
            Console.WriteLine("ShouldRender - DEBUT");
            return _result;

        }
    }
}